baseURL = "https://dfeyer.go.ttree.space/cdp-2018/"
languageCode = "fr-ch"
theme = "perma"
title = "CDP Vaud-Valais · 9 au 22 juillet 2018"

[[menu.main]]
    name = "Objectifs"
    weight = 1
    url = "/objectifs#content"

[[menu.main]]
    name = "L'équipe"
    weight = 2
    url = "/equipe#content"

[[menu.main]]
    name = "Les lieux"
    weight = 3
    url = "/lieux#content"

[[menu.main]]
    name = "Programme"
    weight = 4
    url = "/programme#content"
