baseURL = "https://dfeyer.go.ttree.space/cdp-2018/"
languageCode = "fr-ch"
theme = "perma"
title = "CDP Vaud-Valais 2018"

[[menu.main]]
    name = "Objectifs"
    weight = 1
    url = "/objectifs"

[[menu.main]]
    name = "L'équipe"
    weight = 2
    url = "/equipe"

[[menu.main]]
    name = "Les lieux"
    weight = 3
    url = "/lieux"

[[menu.main]]
    name = "Programme"
    weight = 4
    url = "/programme"
