baseURL = "https://dfeyer.go.ttree.space/cdp-2018/"
languageCode = "fr-ch"
theme = "perma"
title = "CDP Vaud-Valais · 9 au 22 juillet 2018"

[params]
teamSections = ["formateurs", "intervenants", "personnes"]

[[menu.main]]
    name = "Objectifs"
    weight = 1
    url = "/objectifs#content"

[[menu.main]]
    name = "L'équipe"
    weight = 2
    url = "/intervenants#content"

[[menu.main]]
    name = "Le programme"
    weight = 3
    url = "/programme#content"

[[menu.main]]
    name = "Les lieux"
    weight = 5
    url = "/lieux#content"
