backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Histoire de la permaculture"
        name: "histoire-de-la-permaculture"
        file: "content/histoire-de-la-permaculture.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "2018 / Inscription"
        name: "2018-inscription"
        file: "content/2018/inscription.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "2018 / Objectifs"
        name: "2018-objectif"
        file: "content/2018/objectifs.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "2018 / Programme"
        name: "2018-programme"
        file: "content/2018/programme.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
  - name: "formateur"
    label: "2018 / Formateurs"
    folder: "content/2018/equipe/formateurs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "people"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Certified", name: "certified", widget: "boolean"}
      - {label: "Tags", name: "thumbnail", widget: "list", default: ["staff", "2018"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "intervenant"
    label: "2018 / Intervenants"
    folder: "content/2018/equipe/intervenants"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "people"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Certified", name: "certified", widget: "boolean"}
      - {label: "Tags", name: "thumbnail", widget: "list", default: ["staff", "2018"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "staff"
    label: "2018 / Staff"
    folder: "content/2018/equipe/staff"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "people"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Certified", name: "certified", widget: "boolean"}
      - {label: "Tags", name: "thumbnail", widget: "list", default: ["staff", "2018"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "lieu"
    label: "2018 / Lieu"
    folder: "content/2018/lieux"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Type", name: "type", widget: "hidden", default: "location"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Locality", name: "locality", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "home"
    label: "2018 / Home"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
